### ISSUE TITLE
scenario context

### ISSUE THREAD

**Issue by johnathanseal-datacom** [SupreetKhattra/SmartlyUITestAutomationExcercise-main#10]
More of a question than an issue.
You use scenariocontext in the step definition class.
Is there any value in passing the scenario context to the page classes?

**Comment by SupreetKhattra** [comment]
Hey Jonathon, below are some of the findings from internet which suggest that the ScenarioContext should remain in StepDefinition class and not be passed down to pages classes.

"Passing the ScenarioContext to page classes might not be necessary in most cases. The ScenarioContext is typically used in step definitions to share state across steps within the same scenario. It provides a way to pass data between steps and even between step definition classes.

However, page classes are generally meant to represent the elements and behaviors of a specific page in your application. They encapsulate the interactions with the UI elements on that page. Therefore, there's usually no need for them to directly access or modify the ScenarioContext, as it's more related to the flow and state of the scenario rather than the specific behavior of the page.

Instead, if there's a need to share information between step definitions and page classes, it's better to pass only the required data (like parameters) directly to the methods of the page classes. This keeps the responsibilities clear and avoids coupling the page classes with testing framework-specific context objects like ScenarioContext.

So, in most cases, you can safely avoid passing the ScenarioContext to your page classes unless you have a specific requirement that necessitates it. Instead, rely on passing data through method parameters or using other design patterns like dependency injection if needed. This keeps your page classes more reusable and decoupled from the testing framework."
